application:
    gateway:
        url: http://localhost:8050
eureka:
    client:
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true

hibernate:
    cache:
        use_query_cache: true
        use_second_level_cache: false
    dialect: org.hibernate.dialect.PostgreSQL9Dialect
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                engine:
                    jdbc:
                        env:
                            internal:
                                LobCreatorBuilderImpl: ERROR
                stat: TRACE
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8081
    servlet:
        context-path: /client-webapp

spring:
    application:
        name: client-webapp
    cloud:
        config:
            server:
                git:
                    uri: S:\Git\jcoursescloud\config-repo
            uri: http://localhost:8888
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        url: jdbc:postgresql://localhost:5432/jcourses
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
                generate_statistics: true
        show-sql: true
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    profiles:
        active: dev
    devtools:
        restart:
            additional-paths: .
