eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
    server:
        eviction-interval-timer-in-ms: 10000
        registry-sync-retry-wait-ms: 10
server:
    port: 8761
spring:
    application:
        name: eureka-server

