application:
  gateway:
    url: http://localhost:8050

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true

spring:
  application:
    name: service-layer
  profiles:
    active: dev

  cloud:
    config:
      name: config-server
      server:
        git:
          uri: S:\Git\jcoursescloud\config-repo

  datasource:
    url: jdbc:postgresql://localhost:5432/jcourses
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        use_query_cache: true
        use_second_level_cache: false
    show-sql: true

server:
  port: 8181
  servlet:
    context-path: /service-layer

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        engine:
          jdbc:
            env:
              internal:
                LobCreatorBuilderImpl: ERROR
        stat: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
