hibernate:
  cache:
    use_query_cache: true
    use_second_level_cache: false
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        engine:
          jdbc:
            env:
              internal:
                LobCreatorBuilderImpl: ERROR
        stat: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
spring:
  application:
    name: security
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    show-sql: true
server:
  port: 9100

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka