management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8888
spring:
    cloud:
        config:
            server:
                git:
                    clone-on-start: true
                    uri: S:\Git\cloudcourses\config-repo
    config:
        name: configserver
